export const FETCH_GEO_REQUESTED = 'FETCH_GEO_REQUESTED';
export const FETCH_GEO_SUCCEEDED = 'FETCH_GEO_SUCCEEDED';
export const FETCH_GEO_FAILED = 'FETCH_GEO_FAILED';
export const GEOLOCATION_KEY = process.env.REACT_APP_API_KEY;
